### ISSUE TITLE
Adjust Front-End

### ISSUE THREAD

**Issue by spereira15** [k-pineda/ShelfSwap#8]
- Get rid of outdated imports/functionalities.
- Get rid of unnecessary components, pages, etc.
- Adapt the boilerplate Front-end to our Application.

_**NOTE**: Adjusting the Front-end doesn't mean styling it. It just means ensuring our application functions as desired. I'd say ignore Styles for the moment, we can review later when our app's functionality is polished._

**Comment by k-pineda** [comment]
completed
